/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "smjptcyunfprhombsnbx"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNtanB0Y3l1bmZwcmhvbWJzbmJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMyNDY2ODIsImV4cCI6MjA4ODgyMjY4Mn0.LzCQbi6-n9bnw7hL0vyP7bDnI-vY_YqZxPkIzTBEQEc"